name: cart_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none' 
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"
  

dependencies:
  flutter:
    sdk: flutter
  models:
    path: ../models
  uuid: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
